### ISSUE TITLE
download contains issues of other users

### ISSUE THREAD

**Issue by voomdoon** [osm-fr/osmose-frontend#467] opened 2023-07-03 14:42 UTC
e.g download my issues from https://osmose.openstreetmap.fr/en/api/0.3/issues.csv?&usename=voomdoon

it starts with

```
uuid,source,item,class,level,title,subtitle,country,analyser,timestamp,username,lat,lon,elems
7b5f9ce9-a51b-2ad3-fc73-653f9a932756,34,2060,10,3,Invalid addr:housenumber value,,madagascar,Sax,2023-07-01 20:21:30+00:00,[''],-18.9801287,47.5446418,node4109415494
```

but https://www.openstreetmap.org/node/4109415494/history does not list my user...

looks like its the same content for all users. Even users with no issues getting the same file...

**Comment by mnalis** [comment] 2023-07-07 21:29
I've just went to report it, the problem is that clicking on link like:

http://osmose.openstreetmap.fr/en/byuser/Matija%20Nalis

produces wrong URLs for `.rss`, `.gpx`, `.csv` etc links on that page. I.e. it might lead to

In particular, that `usename=` should be `username=` instead. If that is fixed by manually editing the URL, it works.

e.g. RSS should not lead to:
https://osmose.openstreetmap.fr/en/api/0.3/issues.rss?&usename=Matija%20Nalis
but to:
https://osmose.openstreetmap.fr/en/api/0.3/issues.rss?&username=Matija%20Nalis

**Closed** 2023-07-08 08:19 UTC

**Comment by frodrigo** [comment] 2023-07-08 08:24
Thank you all. The fix is now deployed.
