### ISSUE TITLE
Osmose not working anymore on Safari (no issue markers)

### ISSUE THREAD

**Issue by SelfishSeahorse** [osm-fr/osmose-frontend#108] opened 2018-09-10 12:15 UTC
I've just noticed that http://osmose.openstreetmap.fr/ doesn't work anymore on Safari (version 11.1.2), that is the issue markers don't appear anymore:

![untitled](https://user-images.githubusercontent.com/14875493/45296724-43185e80-b503-11e8-9fa5-1f44f273c9aa.png)

On Firefox (version 62.0), they still appear. A few weeks ago the website worked on Safari (same version 11.1.2 as far as i can remember).

**Comment by frodrigo** [comment] 2018-09-11 19:44
There is any JS errors (in the console ?)

**Comment by SelfishSeahorse** [comment] 2018-09-11 19:58
> There is any JS errors (in the console ?)

[Error] Failed to load resource: the server responded with a status of
404 (Not Found)
http://osmose.openstreetmap.fr/en/map/issues/6/30/22.mvt?
[Error] Failed to load resource: the server responded with a status of
404 (Not Found)
http://osmose.openstreetmap.fr/en/map/issues/6/29/22.mvt?
[Error] Failed to load resource: the server responded with a status of
404 (Not Found)
http://osmose.openstreetmap.fr/en/map/issues/6/29/21.mvt?
[Error] Failed to load resource: the server responded with a status of
404 (Not Found)
http://osmose.openstreetmap.fr/en/map/issues/6/29/23.mvt?

**Comment by frodrigo** [comment] 2018-09-12 12:31
I test quickly on Mac with Safari, tiles are OK.
The 404 on tiles you list are normal. There are empty tiles on water.
The problem is more on display of the tiles data.

**Comment by jocelynj** [comment] 2018-11-22 19:38
@SelfishSeahorse Are you still able to access osmose from another browser as a workaround ?

**Comment by pyrog** [comment] 2019-02-06 19:43
This issue is still there 😢

> Osmose frontend was upgraded the 7th of sept

Commit 96bb84affe02c10a6cf14d2e71e23e5c7b15f25b ?

**Comment by frodrigo** [comment] 2019-02-06 22:32
@pyrog nobody with Safari able to debug around :-/

**Comment by pyrog** [comment] 2019-02-26 08:30
Hi Frédéric,

I tried to put a breakpoint in the source code. But there is a lot of scripts.
Could you tell me where to search ?
I could compare step by step the behaviours between Safari and Chrome.

—
Yves

**Comment by frodrigo** [comment] 2019-02-26 12:05
Look at this part of code:
https://github.com/osm-fr/osmose-frontend/blob/master/static/map/Osmose.Marker.js

**Comment by pyrog** [comment] 2019-05-09 09:02
Today, Osmose work fine with Safari 😃
Thanks

**Comment by frodrigo** [comment] 2019-05-09 09:04
Glad to know. Maybe Safari was fixed inside of Osmose.

**Closed by frodrigo** 2019-05-09 09:04 UTC
Labels: bug, help-wanted
